### ISSUE TITLE
Cannot connect to cluster when running `bundle exec karakfa s`

### ISSUE THREAD

**Issue by cxk280** [karafka/example-app#32]
I'm trying to run the example app in conjunction with running a Kafka server using Apache's [Quick Start instructions](https://kafka.apache.org/quickstart). However, when I try to do so, Karafka cannot connect to the cluster.

It returns the errors `INFO -- : Fetching cluster metadata from kafka://172.17.0.3:9092` and `ERROR -- : Timed out while trying to connect to 172.17.0.3:9092: Operation timed out`. I'm running Zookeeper and Kafka according to the Quick Start instructions, and I also tried starting new nodes, but it still didn't work. I can send and receive messages to myself on the Kafka side, so that seems to be working.

I suspect there's an issue with matching the ports, but I'm not entirely sure how to properly resolve this. Please help.

**Comment by mensfeld** [comment]
Well you can just replace the ips with the once on which you have Kafka :) - it seems that they set it up on the localhost, so just replace "172.17.0.3" with a localhost. The rest should be fine. I will replace this "weird" ip address with a localhost in the repo as well. If it helps, please close the issue.

**Comment by mensfeld** [comment]
Also, please try pulling the example app latest changes as it seems that a localhost is there by default.

**Comment by cxk280** [comment]
Pulling latest changes fixed it. Thank you!

**Comment by mensfeld** [comment]
Anytime. Ping me if it doesn't help.

**Comment by mensfeld** [comment]
Since you were playing with workers and redis - I'll assume that you've managed to get it up and running. Closing. Feel free to reopen in case of any problems.
